Trident v21.04 templates added
IBM/ibm-satellite-storage pull request #118
Opened 2021-06-04 20:35 UTC by ntap-troy

I removed the 21.01 directories, added 21.04 directories, and updated all of the config files in:
- config-templates/netapp/netapp-ontap-nas/21.04
- config-templates/netapp/netapp-ontap-san/21.04
- config-templates/netapp/netapp-trident/21.04

2021-06-10 20:37 UTC, derekpoindexter requested changes
I left a few commit suggestions

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-nas/21.04/README.md
> +You can use the `netapp-ontap-nas` Satellite storage template to deploy NetApp storage drives which you can use dynamically provision and mange file volumes in your ONTAP NAS.
```suggestion
You can use the `netapp-ontap-nas` Satellite storage template to deploy NetApp storage drivers which you can use dynamically provision and manage file volumes in your ONTAP NAS.
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-nas/21.04/README.md
> +For information on creating and managing QoS Policy groups, please refer to the [ONTAP 9 Storage Management documentation](https://docs.netapp.com/ontap-9/index.jsp).
```suggestion
For information on creating and managing QoS Policy groups, please refer to the [ONTAP 9 Storage Management documentation](https://docs.netapp.com/ontap-9/index.jsp).


```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-san/21.04/README.md
> +You can use the `netapp-ontap-san` Satellite storage template to deploy NetApp storage drives which you can use dynamically provision and manage LUNs in your ONTAP SAN.
```suggestion
You can use the `netapp-ontap-san` Satellite storage template to deploy NetApp storage drivers which you can use dynamically provision and manage LUNs in your ONTAP SAN.
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-trident/21.04/README.md
> +Trident deploys in Kubernetes clusters as pods and provides dynamic storage orchestration services for your Kubernetes workloads. It has been designed from the ground up to help you meet the persiste
```suggestion
Trident provides dynamic storage orchestration services for your Kubernetes workloads. It has been designed from the ground up to help you meet the persistence demands of your containerized applications by using industry standard interfaces like the Container Storage Interface (CSI).
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-nas/21.04/README.md
> +**Planning consideration for Location Admin**
```suggestion
**Planning considerations for the Satellite Location Admin**
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-nas/21.04/metadata.json
> +      "value": "Install netapp-trident before installing ontap-nas driver."
```suggestion
      "value": "Install the netapp-trident driver before installing the ontap-nas driver."
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-san/21.04/README.md
> +* Make sure `netapp-trident` is deployed on the target cluster
```suggestion
* Make sure `netapp-trident` is deployed on the target cluster.
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-san/21.04/README.md
> +* Share following details with Location Admin
```suggestion
* Share following details with Location Admin.
```

2021-06-10 20:37 UTC, derekpoindexter commented on config-templates/netapp/netapp-ontap-san/21.04/README.md
> +**Planning consideration for Infra Admin**
```suggestion
**Planning considerations for the Infrastructure Admin**
```

2021-06-25 03:31 UTC, nkkashyap requested changes

2021-06-25 03:31 UTC, nkkashyap commented on config-templates/netapp/netapp-ontap-san/21.04/README.md
> +| `ntap-block-default` | Ontap-SAN | Block | n/a | Delete |
Update the storage class names to `sat-netapp-block-gold`,`sat-netapp-block-silver`, `sat-netapp-block-bronze` and `sat-netapp-block-default`

2021-06-25 03:31 UTC, nkkashyap commented on config-templates/netapp/netapp-ontap-nas/21.04/README.md
> +
Update the storage class names to `sat-netapp-file-gold`,`sat-netapp-file-silver`, `sat-netapp-file-bronze` and `sat-netapp-file-default`

2021-06-30 20:25 UTC, ntap-troy reviewed
Updated README files with links to NetApp Installation & Configuration documentation

2021-07-20 13:00 UTC, nkkashyap commented on config-templates/netapp/netapp-trident/21.04/README.md
> +ibmcloud sat storage config create --name "trident-conf" --template-name "netapp-trident" --template-version "21.04"
```suggestion
ibmcloud sat storage config create --name "trident-conf" --location <location id> --template-name "netapp-trident" --template-version "21.04"
```

2021-07-20 13:04 UTC, nkkashyap approved these changes
Looks good 
Pls update the `sat storage config create` cmd in README to pass location id

2021-07-27 08:07 UTC, nkkashyap requested changes

2021-07-27 08:07 UTC, nkkashyap commented on config-templates/netapp/netapp-ontap-san/21.04/storage-class-parameters.json
> +	}
Define parameter for `fsType`
```
	}, {
	  "description": "The file system type.",
	  "displayname": "File System",
	  "name": "fsType",
	  "templateKeyName": [
		  "fsType"
	  ],
	  "default": "ext4",
	  "required": "false",
	  "category": "config",
	  "type": "text"
	}
```

2021-07-28 11:22 UTC, nkkashyap approved these changes
Looks good

2021-07-30 17:59 UTC, derekpoindexter approved these changes

2021-07-30 20:24 UTC, merged