Azure Disk Template 1.4.0
IBM/ibm-satellite-storage pull request #127
Opened 2021-06-25 08:18 UTC by gauravAggrhari

## Test Results

**get pods in `kube-system`**
```
% kubectl get pods -n kube-system | grep azure disk
NAME                                        READY   STATUS    RESTARTS   AGE
csi-azuredisk-controller-849d854b96-6jbjg   5/5     Running   0          6m20s
csi-azuredisk-controller-849d854b96-lkplx   5/5     Running   0          6m20s
csi-azuredisk-node-7qwlj                    3/3     Running   6          6m20s
csi-azuredisk-node-8xm4c                    3/3     Running   6          6m20s
csi-azuredisk-node-snsdb                    3/3     Running   6          6m20s
```

**get storage class**
```
% kubectl get sc        
NAME                             PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
sat-azure-block-bronze           disk.csi.azure.com   Delete          Immediate              true                   164m
sat-azure-block-bronze-metro     disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   164m
sat-azure-block-gold             disk.csi.azure.com   Delete          Immediate              true                   164m
sat-azure-block-gold-metro       disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   164m
sat-azure-block-platinum         disk.csi.azure.com   Delete          Immediate              true                   164m
sat-azure-block-platinum-metro   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   164m
sat-azure-block-silver           disk.csi.azure.com   Delete          Immediate              true                   164m
sat-azure-block-silver-metro     disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   164m
```

**get secret**
```
% kubectl get secret azure-cloud-provider -n kube-system
NAME                   TYPE     DATA   AGE
azure-cloud-provider   Opaque   1      166m
```

**get PVC**
```
% kubectl get pvc                                    
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
pvc-azuredisk   Bound    pvc-eb037445-b832-4cd1-8c34-fb6125c00832   10Gi       RWO            sat-azure-block-gold-metro   17s
```

**get pod which attaches the above PVC**
```
% kubectl get pods               
NAME              READY   STATUS    RESTARTS   AGE
nginx-azuredisk   1/1     Running   0          27s
```

**Verify if the data is being written**
```
% kubectl exec -it nginx-azuredisk -- tail -f /mnt/azuredisk/outfile                   
Tue Jun 22 06:16:22 UTC 2021
Tue Jun 22 06:16:23 UTC 2021
Tue Jun 22 06:16:24 UTC 2021
Tue Jun 22 06:16:25 UTC 2021
Tue Jun 22 06:16:26 UTC 2021
Tue Jun 22 06:16:27 UTC 2021
Tue Jun 22 06:16:28 UTC 2021
Tue Jun 22 06:16:29 UTC 2021
Tue Jun 22 06:16:30 UTC 2021
Tue Jun 22 06:16:31 UTC 2021
Tue Jun 22 06:16:32 UTC 2021
Tue Jun 22 06:16:33 UTC 2021
```

2021-07-03 14:58 UTC, nkkashyap approved these changes
LGTM
A minor comment in readme

2021-07-03 14:58 UTC, nkkashyap commented on config-templates/azure/azuredisk-csi-driver/1.4.0/README.md
> +```
pls add `--location <location>` option

2021-07-05 12:24 UTC, derekpoindexter requested changes

2021-07-05 12:24 UTC, derekpoindexter commented on config-templates/azure/azuredisk-csi-driver/1.4.0/README.md
> +    - ZRS disk support(Preview)
```suggestion
- ZRS disk support(Preview)
```

2021-07-05 12:24 UTC, derekpoindexter commented on config-templates/azure/azuredisk-csi-driver/1.4.0/custom-parameters.json
> +        "description": "cloud-config : This is a base64 encoded string generated from azure.json",
```suggestion
        "description": "cloud-config : The base64 encoded string generated from the azure.json config file.",
```

2021-07-05 12:24 UTC, derekpoindexter commented on config-templates/azure/azuredisk-csi-driver/1.4.0/metadata.json
> +    "description": "AZURE DISK CSI Driver version 1.4.0[BETA]",
```suggestion
    "description": "[Beta] - Azure Disk CSI Driver",
```

2021-07-05 12:24 UTC, derekpoindexter commented on config-templates/template_list.json
> +    "displayname": "AZUREDISK CSI Driver",
```suggestion
    "displayname": "Azure Disk CSI Driver",
```

2021-07-05 12:24 UTC, derekpoindexter commented on config-templates/template_list.json
> +    "Description": "AZUREDISK CSI Driver[BETA].",
```suggestion
    "Description": "Azure Disk CSI Driver",
```

2021-07-05 12:40 UTC, derekpoindexter commented on config-templates/azure/azuredisk-csi-driver/1.4.0/metadata.json
> +            "value": "AZURE"
```suggestion
            "value": "Azure"
```

2021-07-06 17:41 UTC, derekpoindexter approved these changes

2021-07-09 14:41 UTC, merged