Renamed OCS to ODF
IBM/ibm-satellite-storage pull request #129
Opened 2021-07-05 05:09 UTC by Shirisha-S-Rao-1

2021-07-05 09:03 UTC, akgunjal requested changes
Check if we need the changes for 4.6 version as well as its still actively supported. Also need image update for 4.6 for PSIRT

2021-07-05 09:03 UTC, akgunjal commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The billing type for your ODFconfiguration.",
Add a space between ODFconfiguration

2021-07-05 09:03 UTC, akgunjal commented on config-templates/redhat/odf-remote/4.7/deployment.yaml
> +            image: "icr.io/obs/ibm-ocs-operator:v4.7.5"
Update image to `v4.7.6`

2021-07-05 09:03 UTC, akgunjal commented on config-templates/redhat/odf-remote/4.7/metadata.json
> +  "description": "ODFtemplate for openshift 4.7 (Remote storage)",
Add a space between ODFtemplate

2021-07-06 17:36 UTC, derekpoindexter commented on config-templates/template_list.json
> +    "displayname": "OpenShift Data Foundation storage for local devices",
```suggestion
    "displayname": "OpenShift Data Foundation for local devices",
```

2021-07-06 17:36 UTC, derekpoindexter commented on config-templates/template_list.json
> +    "Description": "OpenShift Data Foundation storage for local devices.",
```suggestion
    "Description": "OpenShift Data Foundation for local devices.",
```

2021-07-06 17:36 UTC, derekpoindexter commented on config-templates/template_list.json
> +    "displayname": "OpenShift Data Foundation storage for remote storage",
```suggestion
    "displayname": "OpenShift Data Foundation for remote storage",
```

2021-07-06 17:37 UTC, derekpoindexter commented on config-templates/template_list.json
> +    "Description": "OpenShift Data Foundation storage for remote storage.",
```suggestion
    "Description": "OpenShift Data Foundation for remote storage.",
```

2021-07-09 17:00 UTC, akgunjal approved these changes
LGTM

2021-07-13 10:19 UTC, nkkashyap approved these changes
Looks good

2021-07-13 10:19 UTC, merged