Add vpc driver template
IBM/ibm-satellite-storage pull request #154
Opened 2021-10-19 10:40 UTC by meghnasiingh

Signed-off-by: Meghna Singh <Meghna.Singh1@ibm.com>

2021-11-18 06:37 UTC, meghnasiingh commented
Test results
-------------------
Create config and assignment
```
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ ibmcloud sat storage config create --name vpc-template-new --template-name ibm-vpc-block-csi-driver --template-version 4.0.1 --param "g2_resource_group_id=<rg-id>" --param "g2_riaas_endpoint_url=https://us-south.iaas.cloud.ibm.com" --param "g2_token_exchange_endpoint_url=https://iam.cloud.ibm.com" --param "g2_api_key=<apikey>" --location c5e16s3d06umklja1i5g --source-org=meghnasiingh --source-branch=add-temp
Creating Satellite storage configuration...
OK
Storage configuration 'vpc-template-new' was successfully created with ID 'f17d8c6e-8feb-4475-a81d-19f823c55540'.
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$
```
```
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ ibmcloud sat storage assignment create --name vpc-csi-driver --config vpc-template-new --cluster c5e1sj8d0ks5qe9v6t70
Creating assignment...
FAILED
The service is currently unavailable. Wait a few minutes and try again. MS Backend Error is : 'ST0037: Failed to fetch {{.ObjectType}} '{{.ObjectIdentifier}}'. Backend Error - {{.BackendError}}' (ST0006)

Incident ID: 3f0921e0-f2c5-414a-acac-dd5664c93db3

Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ ibmcloud sat storage assignment ls -c c5e1sj8d0ks5qe9v6t70
OK
Name             ID                                     Configuration      Version                Creator                                             Created   
vpc-csi-driver   24d7b45e-f0df-41b7-88cd-f5af09dad2c6   vpc-template-new   vpc-template-new_v01   IBMid-310000AJGN,54e2afcb5f8eea01bfc3fde0ac755f1d   2021-11-18T05:59:49.079Z   
vpc-csi-driver   19ee3b06-e5cf-4f4b-8e3d-a85f8982db11   vpc-template-new   vpc-template-new_v01   IBMid-310000AJGN,54e2afcb5f8eea01bfc3fde0ac755f1d   2021-11-18T05:59:57.425Z   
vpc-csi-driver   1ca8298c-7eb0-454d-9d6c-0727958a7d81   vpc-template-new   vpc-template-new_v01   IBMid-310000AJGN,54e2afcb5f8eea01bfc3fde0ac755f1d   2021-11-18T05:59:59.317Z   
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ 
```
- Check if driver and node-label-watcher pods are running
```
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ kubectl get pods -n kube-system | grep vpc 
ibm-vpc-block-csi-controller-0                    5/5     Running   0          88s
ibm-vpc-block-csi-node-frqqg                      3/3     Running   0          88s
ibm-vpc-block-csi-node-mdm5l                      3/3     Running   1          88s
ibm-vpc-block-csi-node-mdvtd                      3/3     Running   0          88s
vpc-node-label-updater-6cd479678-s87zs            1/1     Running   0          89s
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ 
```
- Check if node-label watcher successfully added required node labels or not
```
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ kubectl get nodes --show-labels
NAME                      STATUS   ROLES           AGE   VERSION           LABELS
sat-vpc-us-workernode01   Ready    master,worker   43d   v1.20.0+9689d22   arch=amd64,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=upi,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-south,failure-domain.beta.kubernetes.io/zone=us-south-1,ibm-cloud.kubernetes.io/iaas-provider=upi,ibm-cloud.kubernetes.io/internal-ip=10.240.1.5,ibm-cloud.kubernetes.io/machine-type=upi,ibm-cloud.kubernetes.io/os=REDHAT_7_64,ibm-cloud.kubernetes.io/region=us-south,ibm-cloud.kubernetes.io/worker-id=0717_af8e276b-e242-4037-bbb0-4231adad8cc4,ibm-cloud.kubernetes.io/worker-pool-id=c5e1sj8d0ks5qe9v6t70-9053d9d,ibm-cloud.kubernetes.io/worker-pool-name=default,ibm-cloud.kubernetes.io/worker-version=4.7.31_1533_openshift,ibm-cloud.kubernetes.io/zone=zone-1,kubernetes.io/arch=amd64,kubernetes.io/hostname=sat-vpc-us-workernode01,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=upi,node.openshift.io/os_id=rhel,privateVLAN=1,topology.kubernetes.io/region=us-south,topology.kubernetes.io/zone=us-south-1
sat-vpc-us-workernode02   Ready    master,worker   43d   v1.20.0+9689d22   arch=amd64,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=upi,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-south,failure-domain.beta.kubernetes.io/zone=us-south-2,ibm-cloud.kubernetes.io/iaas-provider=upi,ibm-cloud.kubernetes.io/internal-ip=10.240.64.4,ibm-cloud.kubernetes.io/machine-type=upi,ibm-cloud.kubernetes.io/os=REDHAT_7_64,ibm-cloud.kubernetes.io/region=us-south,ibm-cloud.kubernetes.io/worker-id=0727_5c71f17f-8cbc-433c-9c8e-425ca98b5b87,ibm-cloud.kubernetes.io/worker-pool-id=c5e1sj8d0ks5qe9v6t70-9053d9d,ibm-cloud.kubernetes.io/worker-pool-name=default,ibm-cloud.kubernetes.io/worker-version=4.7.31_1533_openshift,ibm-cloud.kubernetes.io/zone=zone-1,kubernetes.io/arch=amd64,kubernetes.io/hostname=sat-vpc-us-workernode02,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=upi,node.openshift.io/os_id=rhel,privateVLAN=1,topology.kubernetes.io/region=us-south,topology.kubernetes.io/zone=us-south-2
sat-vpc-us-workernode03   Ready    master,worker   43d   v1.20.0+9689d22   arch=amd64,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=upi,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-south,failure-domain.beta.kubernetes.io/zone=us-south-3,ibm-cloud.kubernetes.io/iaas-provider=upi,ibm-cloud.kubernetes.io/internal-ip=10.240.128.4,ibm-cloud.kubernetes.io/machine-type=upi,ibm-cloud.kubernetes.io/os=REDHAT_7_64,ibm-cloud.kubernetes.io/region=us-south,ibm-cloud.kubernetes.io/worker-id=0737_d5ff2f47-0c01-400b-b5a5-8556236993a0,ibm-cloud.kubernetes.io/worker-pool-id=c5e1sj8d0ks5qe9v6t70-9053d9d,ibm-cloud.kubernetes.io/worker-pool-name=default,ibm-cloud.kubernetes.io/worker-version=4.7.31_1533_openshift,ibm-cloud.kubernetes.io/zone=zone-1,kubernetes.io/arch=amd64,kubernetes.io/hostname=sat-vpc-us-workernode03,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=upi,node.openshift.io/os_id=rhel,privateVLAN=1,topology.kubernetes.io/region=us-south,topology.kubernetes.io/zone=us-south-3
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$
```
we can see labels are added successfully
- Logs of node-label-watcher
```
Meghnas-MacBook-Pro:vpc-node-label-updater meghna$ kubectl logs -f vpc-node-label-updater-6cd479678-s87zs -n kube-system
{"level":"info","timestamp":"2021-11-18T06:00:02.973Z","caller":"nodewatcher/node_watcher.go:48","msg":"Starting the node watcher for labelling the vpc worker nodes","watcher-name":"vpc-node-label-updater"}
{"level":"info","timestamp":"2021-11-18T06:00:02.982Z","caller":"nodewatcher/utils.go:187","msg":"parsing conf file","watcher-name":"vpc-node-label-updater","confpath":"/etc/storage_ibmc/slclient.toml"}
{"level":"info","timestamp":"2021-11-18T06:00:03.181Z","caller":"nodewatcher/utils.go:104","msg":"Successfully got access token in exchange of apikey","watcher-name":"vpc-node-label-updater"}
{"level":"info","timestamp":"2021-11-18T06:00:03.282Z","caller":"nodewatcher/node_watcher.go:127","msg":"Processing node.","watcher-name":"vpc-node-label-updater","WorkerNodeName":"sat-vpc-us-workernode01"}
{"level":"info","timestamp":"2021-11-18T06:00:03.282Z","caller":"nodewatcher/node_watcher.go:153","msg":"Updating labels for the new node, ","watcher-name":"vpc-node-label-updater","workerNodeName":"sat-vpc-us-workernode01"}
{"level":"info","timestamp":"2021-11-18T06:00:03.282Z","caller":"nodewatcher/utils.go:110","msg":"Getting details for worker","watcher-name":"vpc-node-label-updater","workerName":"sat-vpc-us-workernode01"}
{"level":"info","timestamp":"2021-11-18T06:00:03.935Z","caller":"nodewatcher/utils.go:173","msg":"Successfully got the details of worker node","watcher-name":"vpc-node-label-updater"}
{"level":"info","timestamp":"2021-11-18T06:00:03.998Z","caller":"nodewatcher/node_watcher. [...]

2021-11-22 06:59 UTC, nkkashyap requested changes

2021-11-22 06:59 UTC, nkkashyap commented on config-templates/template_list.json
> +    "displayname": "IBM VPC Block CSI driver",
Pls add [Beta] 
`"IBM VPC Block CSI driver"` => `"[Beta] IBM VPC Block CSI driver"`
and `"Description": "IBM VPC Block CSI driver, Provides block storage on VPC.",` => `"Description": "[Beta] IBM VPC Block CSI driver, Provides block storage on VPC.",`

2023-10-27 09:29 UTC, nkkashyap commented
Stale

2023-10-27 09:29 UTC, closed without merging