Create templates for Azure file with nfs protocol.
IBM/ibm-satellite-storage pull request #166
Opened 2021-12-22 05:56 UTC by boddumanohar

Create templates for Azure file with nfs protocol.

2022-01-27 12:27 UTC, boddumanohar commented
added readme.md file. That has usage instructions along with the output of the screenshots.

2022-01-28 16:36 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/README.md
> +
Can you also provide an example deployment? And verify data write

2022-02-03 14:45 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/README.md
> +| `vnetName` | Required | the `vmType`. This value of this can be taken from the `azure.json` [conifg file](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/azure.js
```suggestion

| Parameter | Required? | Description | 
| --- | --- | --- |
| `tenantId` | Required | The Azure tenant ID that you want to use for your configuration. Follow the Azure documentation to find your [tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant){: external} or run the  |
| `subscriptionId` | Required | Your Azure subscription ID. From the Azure portal, search for `Subscription` to find a list of your subscriptions. You can also find this value by running the `az account subscription list` command. |
| `aadClientId` | Required | Your Azure Active Directory Client ID. You can find this value by running the `az identity list` command. |
| `aadClientSecret` | Required | Your Azure Active Directory Client Secret. |
| `resourceGroup` | Required | The name of your Azure resource group. You can find this value by running the `az group list` command. |
| `location` | Required | The location of your Azure hosts. For example `useast` |
| `vmType` | Required | The virtual machine type. You can find this value by running the `az vm list` command. For example: `standard` or `VMSS`. |
| `securityGroupName` | Required | The security group name. You can find this parameters by running the `az network nsg list` command. |
| `vnetName` | Required | The name of the virtual network. You can find this value by running the `az network vnet subnet list` command. |
```

2022-02-04 14:35 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/README.md
> +| `tenantId` | Required | The Azure tenant ID that you want to use for your configuration. Follow the Azure documentation to find your [tenant ID](https://docs.microsoft.com/en-us/azure/active-direct
```suggestion
| `tenantId` | Required | The Azure tenant ID that you want to use for your configuration. Follow the Azure documentation to find your [tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant){: external}. |
```

2022-02-04 14:38 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/README.md
> +| `vnetName` | Required | The name of the virtual network. You can find this value by running the `az network vnet subnet list` command. |
```suggestion
| `tenantId` | Required | The Azure tenant ID that you want to use for your configuration. Follow the Azure documentation to find your [tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant){: external}. |
| `subscriptionId` | Required | Your Azure subscription ID. From the Azure portal, search for `Subscription` to find a list of your subscriptions. You can also find this value by running the `az account subscription list` command. |
| `aadClientId` | Required | Your Azure Active Directory Client ID. You can find this value by reviewing your Activity Directory details in the Azure portal or by running the `az identity list` command. |
| `aadClientSecret` | Required | Your Azure Active Directory Client Secret. You can find this value by reviewing your Activity Directory details in the Azure portal or by running the `az identity list` command. |
| `resourceGroup` | Required | The name of your Azure resource group. You can find this value in the Azure portal or by running the `az group list` command. |
| `location` | Required | The location of your Azure hosts. You can find this value by review the details for your VM in the Azure portal or by running the `az vm show` command. For example `useast` |
| `vmType` | Required | The virtual machine type. Azure virtual machines can be standard or scale sets. You can find your virtual machine type in the Azure portal or by running the `az vm list` command. For example: `standard` or `VMSS`. |
| `securityGroupName` | Required | The security group name. You can find your security group details in the Azure portal or by running the `az network nsg list` command. |
| `vnetName` | Required | The name of the virtual network. You can find this value in the Azure portal or by running the `az network vnet subnet list` command. |
```

2022-02-04 14:42 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/README.md
> +| `vnetName` | Required | The name of the virtual network. You can find this value by running the `az network vnet subnet list` command. |
```suggestion
| `tenantId` | Required | The Azure tenant ID that you want to use for your configuration. Follow the Azure documentation to find your [tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant){: external}. |
| `subscriptionId` | Required | Your Azure subscription ID. From the Azure portal, search for `Subscription` to find a list of your subscriptions. You can also find this value by running the `az account subscription list` command. |
| `aadClientId` | Required | Your Azure Active Directory Client ID. You can find this value in the Azure portal or by running the `az identity list` command. |
| `aadClientSecret` | Required | Your Azure Active Directory Client Secret. You can find this value in the Azure portal. |
| `resourceGroup` | Required | The name of your Azure resource group. You can find this value in the Azure portal or by running the `az group list` command. |
| `location` | Required | The location of your Azure hosts. You can find this value by reviewing your virtual machine details in the Azure portal. For example `useast` |
| `vmType` | Required | The virtual machine type. You can find this value by reviewing your virtual machine details in the Azure portal or by running the `az vm list` command. For example: `standard` or `VMSS`. |
| `securityGroupName` | Required | The security group name. You can find your security group name in the Azure portal by running the `az network nsg list` command. |
| `vnetName` | Required | The name of the virtual network. You can find this value in the Azure portal or by running the `az network vnet subnet list` command. |
```

2022-02-04 14:43 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +    },
```suggestion
```

Gaurav mentioned this is no longer needed/supported? - instead of passing this encoded string, they now pass params

2022-02-04 14:43 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "subscriptionId",
```suggestion
        "description": "Your Azure subscription ID. From the Azure portal, search for 'Subscription' to find a list of your subscriptions. You can also find this value by running the `az account subscription list` command.",
```

2022-02-04 14:45 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "aadClientId",
```suggestion
        "description": "Your Azure Active Directory Client ID. From the Azure portal, search for 'Active Directory'. You can also find this value by running the `az identity list` command.",
```

2022-02-04 14:48 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "location",
```suggestion
        "description": "The location of your Azure hosts. From the Azure portal, search for 'virtual machines'. You can also find this value by running the `az vm list` command. Example location: 'useast'",
```

2022-02-04 14:49 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "aadClientSecret",
```suggestion
        "description": "Your Azure Active Directory Client Secret.",
```

2022-02-04 14:50 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "resourceGroup",
```suggestion
        "description": "The name of your Azure resource group. You can find your resource group detail in the Azure portal or by running the `az group list` command.",
```

2022-02-04 14:53 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "vmType",
```suggestion
        "description": "You can find your virtual machine type in the Azure portal or by running the `az vm list` command. Example types: 'standard' or 'VMSS'.",
```

2022-02-04 14:54 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "securityGroupName",
```suggestion
        "description": "The name of your security group. You can find your security group details in the Azure portal or by running the `az network nsg list` command. ",
```

2022-02-04 14:55 UTC, daniel-p-miller commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "vnetName",
```suggestion
        "description": "The name of the virtual network. You can find this value in the Azure portal or by running the `az network vnet subnet list` command.",
```

2022-02-04 14:55 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "vnetName",
```suggestion
        "description": "The name of the virtual network. You can find this value in the Azure portal or by running the `az network vnet subnet list` command.",
```

2022-02-04 14:59 UTC, derekpoindexter commented on config-templates/azure/azurefile-csi-driver/1.9.0/custom-parameters.json
> +        "description": "tenantId : The base64 encoded string generated from the azure.json config file.",
```suggestion
        "description": "tenantId : The Azure tenant ID that you want to use for your configuration. You can find your tenant ID in the Azure portal or by running the `az account tenant list` command. .",
```

2022-02-04 15:04 UTC, derekpoindexter requested changes
left commit suggestions

2022-02-07 15:19 UTC, derekpoindexter approved these changes

2022-02-08 10:36 UTC, nkkashyap approved these changes

2022-02-08 10:44 UTC, merged