parameter-review
IBM/ibm-satellite-storage pull request #169
Opened 2022-01-27 19:54 UTC by derekpoindexter

updating parameter names and descriptions﻿

2022-02-04 15:05 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "name": "deployment-name",
```suggestion
    "name": "ocs-cluster-name",
```

2022-02-07 15:22 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.8/custom-parameters.json
> +    "description": "The amount of storage available to applications in your cluster. The total storage available to your applications is equal to the OSD size multiplied by the number of OSDs. The de
```suggestion
    "description": "The amount of storage available to the storage daemonset pods. The total storage available to your applications is equal to the osd-size multiplied by the number of storage daemonsets (OSDs). The default value is '100Gi'.",
```

2022-02-07 15:24 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "displayname": "Monitoring storage size",
```suggestion
    "displayname": "Monitoring daemonset disk size",
```

2022-02-07 15:27 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The total amount of storage available to the monitoring daemonset. The default size is '20Gi'.",
```suggestion
    "description": "The total amount of storage available to the monitoring daemonset. The monitoring deamonset consists of 3 monitoring pods that each mount a disk equal to the 'mon-size'. Monitoring data is replicated across these 3 disks. The default size is '20Gi'.",
```

2022-02-07 15:28 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "displayname": "OSD storage size",
```suggestion
    "displayname": "Storage daemonset disk size",
```

2022-02-07 15:28 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The storage class to use when dynamically provisioning devices for the monitor pods.",
```suggestion
    "description": "The storage class to use when dynamically provisioning devices for the storage daemonset pods.",
```

2022-02-07 15:53 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The amount of storage available to applications in your cluster. The total storage available to your applications is equal to the OSD size multiplied by the number of OSDs. The de
```suggestion
    "description": "The amount of storage available to applications in your cluster. The total storage available to your applications is equal to the storage daemonset disk size (osd-size) size multiplied by the number of disks (num-of-osd). The default value is '100Gi'.",
```

2022-02-07 15:53 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.8/custom-parameters.json
> +    "description": "The amount of storage available to the storage daemonset pods. The total storage available to your applications is equal to the osd-size multiplied by the number of storage daemon
```suggestion
    "description": "The amount of storage available to applications in your cluster. The total storage available to your applications is equal to the storage daemonset disk size (osd-size) size multiplied by the number of disks (num-of-osd). The default value is '100Gi'.",
```

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 requested changes

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "displayname": "Storage daemonset disk size",
OSD pod disk size

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The storage class to use when dynamically provisioning devices for the storage daemonset pods.",
The storage class to use when dynamically provisioning devices for the OSD pods.

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The number storage of daemonsets that you want to deploy. Each daemonset consists of 3 pods that each mount one disk equal to the osd-size that you specify. For example if you spe
The number of OSD disks you want to provision. The total storage available to your applications is equal to the num-of-osd multiplied by osd-size. App data is replicated across each zone (Replication factor: 3). The default value is '1'.

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The IAM API key that you want to use in your storage secrets.",
The IAM API key is required for creating the storage secret

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.8/custom-parameters.json
> +    "description": "The total amount of storage available to the monitoring daemonset. The default size is '20Gi'.",
Mon parameters are not required for ODF 4.8 and above

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.8/custom-parameters.json
> +    "description": "The IP addresses the worker nodes where you want to deploy ODF. The minimum number of worker nodes is 3.",
Worker node names. Specify that it's optional

2022-02-09 11:10 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.8/custom-parameters.json
> +    "description": "The location constraint that you want to use when creating your bucket. For example `us-east-standard`.",
Can be changed to something along the lines of --> The location of the COS instance that you want to use when creating your bucket for the noobaa backing-store of your ODF deployment

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 requested changes

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "description": "The local paths on your worker nodes to the volumes you want to use for the OSD pods.",
The disk-by-id of the volumes you want to use for the OSD pods.

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "displayname": "Local paths to OSD volumes.",
disk IDs to OSD volumes

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> -    "description": "The local device path of the MON.",
mon-related parameters are still required in 4.7

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "displayname": "Number of OSD volumes.",
If we make this `number of OSD volumes`, will they input 3 since they've added 3 volumes?

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "description": "The location constraint that you want to use when creating your bucket. For example 'us-east-standard'.",
Mention that this is optional

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-local/4.8/custom-parameters.json
> +    "description": "The number OSD volumes that you want to provision. The total storage available to your apps is equal to the volume size (osd-size) multiplied by the number of volumes (num-of-osd)
The number of

2022-02-10 17:11 UTC, Shirisha-S-Rao-1 commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The storage capacity available to the monitoring pods. The monitoring deamonset consists of 3 monitoring pods that each mount a volume equal to the 'mon-size'. The default size is
mon pods are not created from a daemonset. It's from a deployment

2022-02-14 13:59 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "description": "The local paths on your worker nodes to the volumes you want to use for the OSD pods.",
```suggestion
    "description": "The disk-by-id of the volumes you want to use for the OSD pods. You can find the disk-by-ids by logging into your worker node and running 'ls -l /dev/disk/by-id/'.",
```

2022-02-14 13:59 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "displayname": "Local paths to OSD volumes.",
```suggestion
    "displayname": "OSD volume IDs.",
```

2022-02-14 14:00 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "displayname": "Number of OSD volumes.",
```suggestion
    "displayname": "Number of OSD volumes per worker node.",
```

2022-02-14 14:02 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.7/custom-parameters.json
> +    "description": "The number OSD volumes that you want to provision. The total storage available to your apps is equal to the volume size (osd-size) multiplied by the number of volumes (num-of-osd)
```suggestion
    "description": "The number storage daemonsets that you want to create. The total storage available to your apps is equal to the volume size (osd-size) multiplied by the number of daemonsets (num-of-osd). The default value is '1'.",
```

2022-02-15 16:06 UTC, Shirisha-S-Rao-1 approved these changes
Looks good

2022-02-15 16:22 UTC, derekpoindexter commented on config-templates/redhat/odf-remote/4.7/custom-parameters.json
> +    "description": "The storage capacity available to the monitoring pods. The monitoring deamonset consists of 3 monitoring pods that each mount a volume equal to the 'mon-size'. The default size is
```suggestion
    "description": "The storage capacity available to the monitoring pods. The monitoring deployment consists of 3 monitoring pods that each mount a volume equal to the 'mon-size'. The default size is '20Gi'.",
```

2022-02-17 06:17 UTC, nkkashyap approved these changes
lgtm

2022-02-17 06:17 UTC, merged