4.4.0 template for vpc block csi driver
IBM/ibm-satellite-storage pull request #192
Opened 2022-08-26 04:21 UTC by GunaKKIBM

TODO
1. Testing using this template
2. Update images of vpc node label updater and csi driver in the deployment

2022-10-18 05:00 UTC, prankulmahajan requested changes
For naming convention we can confirm with @mssachan and @arahamad

2022-10-18 05:00 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/4.4.0/deployment.yaml
> +    revision: 1
@mssachan Do we mention `revision:1` in the new template version?

2022-10-18 05:00 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/4.4.0/deployment.yaml
> +    version: 4.4.0
@GunaKKIBM We can rename `4.4.0` to just `4.4` everywhere to be in sync with the naming convention we have in managed environment.

2022-10-18 05:00 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/4.4.0/deployment.yaml
> +              image: icr.io/ibm/ibm-vpc-block-csi-driver:v4.3.5
We need to update this for latest version of 4.4

2022-10-18 05:00 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/4.4.0/deployment.yaml
> +              image: icr.io/ibm/ibm-vpc-block-csi-driver:v4.3.5
Same here

2022-10-18 05:00 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/4.4.0/custom-parameters.json
> +    "description": "The VPC regional endpoint of your VPC cluster in the format https://<region>.iaas.cloud.ibm.com. Example: https://eu-de.iaas.cloud.ibm.com. For more information, see https://cloud
"The VPC regional endpoint of your VPC cluster in the format `https://region.iaas.cloud.ibm.com`. Example: https://eu-de.iaas.cloud.ibm.com. For more information, see https://ibm.biz/vpc-endpoints"
Ref https://github.com/IBM/ibm-satellite-storage/pull/204/files

2022-12-20 10:25 UTC, GunaKKIBM commented
Closing this, as 5.0 is released

2022-12-20 10:25 UTC, closed without merging