Add ridge-csi-driver:1.0.0
IBM/ibm-satellite-storage pull request #200
Opened 2022-09-14 11:25 UTC by alex-ridge

2022-09-14 14:07 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +    version: 1.0.0
```
annotations:
    version: 1.0.0
    revision: 1

2022-09-14 14:13 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +        cloud.ridge.co/managed: 'true'
is the quotes required for this ? If not we can remove.

2022-09-14 14:13 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +            cloud.ridge.co/managed: 'true'
same here

2022-09-14 14:14 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +              emptyDir: { }
Remove the space between `{}`

2022-09-14 14:16 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +                - '--csi-address=$(ADDRESS)'
quotes not required here too.

2022-09-14 14:23 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +              imagePullPolicy: Always
is it required to have `imagePullPolicy: Always` or can it be changed to `imagePullPolicy: IfNotPresent`

2022-09-14 14:25 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +              resources: { }
Remove extra space

2022-09-14 14:35 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +      labels:
Lets add at least these labels to all the resources.
```
app.kubernetes.io/name
app.kubernetes.io/version
```

2022-09-14 15:53 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/storage-class-template.yaml
> +  labels:
Add these labels as well
```
volume-type: "block" # As per user specification; e.g.: block, file or object.
storage-class-preference: "{{ storage-class-preference }}" # As per user specification;e.g.: 1, 2, ...., 99
is-user-defined-class: "true" # As this is a user-defined storage class
```

2022-09-14 15:54 UTC, gauravAggrahari commented on config-templates/ridge/ridge-csi-driver/1.0.0/storage-class-parameters.json
> +
Add this json block
```
{
	"description": "Specify a unique volume tier preference; in the range of 1-99 with 1 being the highest.",
	"displayname": "Storage Class Preference",
	"name": "storage-class-preference",
	"templateKeyName": [
		"storage-class-preference"
	],
	"required": "false",
	"default": "99",
	"category": "config",
	"regex": "^[1-9]([0-9]?)$",
	"type": "text"
  }
```

2022-09-27 13:50 UTC, mssachan requested changes
Need to add RIDGE template entry at https://github.com/IBM/ibm-satellite-storage/blob/develop/config-templates/template_list.json#L129

2022-09-27 13:50 UTC, mssachan commented on config-templates/ridge/ridge-csi-driver/1.0.0/custom-parameters.json
> +    "displayname": "Online expansion",
Is it possible that a location can either support both online & offline volume expansion or support none?

2022-09-27 13:50 UTC, mssachan commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +            cloud.ridge.co/managed: "true"
Lets add these 2 labels here as well so that pods of statefulset would also have those labels
```
app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
```

2022-09-27 13:50 UTC, mssachan commented on config-templates/ridge/ridge-csi-driver/1.0.0/deployment.yaml
> +          labels:
Lets add these 2 labels here as well so that pods of statefulset would also have those labels
```
app.kubernetes.io/name: ridge-csi-driver
        app.kubernetes.io/version: 1.0.0
```

2022-09-27 13:50 UTC, mssachan commented on config-templates/ridge/ridge-csi-driver/1.0.0/storage-class-template.yaml
> +  namespace: kube-system
Storageclass is a cluster scoped resource. Please remove `namespace: kube-system`

2022-09-27 13:50 UTC, mssachan commented on config-templates/ridge/ridge-csi-driver/1.0.0/storage-class-template.yaml
> +    storageclass.kubernetes.io/is-default-class: "true"
I think we should make `storageclass.kubernetes.io/is-default-class` as a configurable parameter

2022-09-27 13:50 UTC, mssachan commented on config-templates/ridge/ridge-csi-driver/1.0.0/metadata.json
> +      "value": "For support contact Ridge"
Please mention support URL as well

2022-09-28 07:55 UTC, alex-ridge commented on config-templates/ridge/ridge-csi-driver/1.0.0/custom-parameters.json
> +    "displayname": "Online expansion",
Yes, the two cases are possible

2022-09-28 07:55 UTC, alex-ridge commented on config-templates/ridge/ridge-csi-driver/1.0.0/metadata.json
> +      "value": "For support contact Ridge"
Is it mandatory? We don't have a support URL (we have an email if we must set something). Also, the installation of Ridge CSI driver should be allowed only on Ridge locations, so users will be able to refer to the Ridge provider details.

2022-09-28 08:02 UTC, alex-ridge commented on config-templates/ridge/ridge-csi-driver/1.0.0/storage-class-template.yaml
> +    storageclass.kubernetes.io/is-default-class: "true"
We will install it automatically on Ridge locations, and I don't think these locations will support any other storage class. Does it make sense to make it configurable?

2022-10-04 05:09 UTC, gauravAggrahari approved these changes
PR LGTM

2022-10-04 09:18 UTC, mssachan approved these changes
LGTM

2022-10-04 09:18 UTC, merged