add local volume 4.11 templates
IBM/ibm-satellite-storage pull request #222
Opened 2022-10-28 12:52 UTC by Bhagyashreek8

2022-10-28 12:52 UTC, Bhagyashreek8 commented
For test results refer this PR - https://github.ibm.com/alchemy-containers/armada-storage-api/pull/4386

2022-11-01 11:19 UTC, mssachan requested changes
PR looks good with minor comments

2022-11-01 11:19 UTC, mssachan commented on config-templates/redhat/local-volume-block/4.11/custom-parameters.json
> +    "default": "false",
Add regex for this param. Refer https://github.com/IBM/ibm-satellite-storage/blob/develop/config-templates/redhat/local-volume-block/4.10/custom-parameters.json#L8

2022-11-01 11:19 UTC, mssachan commented on config-templates/redhat/local-volume-block/4.11/metadata.json
> +      "value": "redhat"
`"redhat"` --> `"Red Hat"`

2022-11-01 11:19 UTC, mssachan commented on config-templates/redhat/local-volume-file/4.11/metadata.json
> +      "value": "redhat"
`"redhat"` --> `"Red Hat"`

2022-11-01 11:19 UTC, mssachan commented on config-templates/redhat/local-volume-file/4.11/custom-parameters.json
> +    "default": "false",
Add regex for this param. Refer https://github.com/IBM/ibm-satellite-storage/blob/develop/config-templates/redhat/local-volume-file/4.10/custom-parameters.json#L8

2022-11-01 11:19 UTC, mssachan commented on config-templates/redhat/local-volume-block/4.11/metadata.json
> +      "value": "1.23,1.24,1.25"
Lets discuss if we need to have `supported-k8s-versions`

2022-11-01 11:19 UTC, mssachan commented on config-templates/redhat/local-volume-file/4.11/custom-parameters.json
> +    "default": "ext4",
Add regex for this param. Refer
https://github.com/IBM/ibm-satellite-storage/blob/develop/config-templates/redhat/local-volume-file/4.10/custom-parameters.json#L42

2022-11-02 10:57 UTC, mssachan commented on config-templates/redhat/local-volume-file/4.11/custom-parameters.json
> +    "required": "false",
Add `"supported-values": ["true", "false"],` as well

2022-11-02 11:07 UTC, mssachan approved these changes
LGTM

2022-11-02 11:07 UTC, merged