CVE and PSIRT ficx for vpc-block 5.0
IBM/ibm-satellite-storage pull request #254
Opened 2022-12-13 07:25 UTC by prankulmahajan

2022-12-14 06:19 UTC, ashimagarg27 requested changes

2022-12-14 06:19 UTC, ashimagarg27 commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "cves": "",
Add cves fixed in new version of ubi image:
expected value:
`"cves": "CVE-2022-42898"`

2022-12-14 06:19 UTC, ashimagarg27 commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
>                  "ubi": "8.6-994",
update ubi image version in previous-release as
`"ubi": "8.7-923"`

Also, update the "new-features" list in previous-release to an empty list as
`"new-features": []`

2022-12-14 07:13 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "cves": "",
Updated

2022-12-14 07:14 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
>                  "ubi": "8.6-994",
Updated

2023-01-02 05:13 UTC, anandkarra approved these changes

2023-01-02 09:01 UTC, mssachan requested changes
LGTM. With a minor comment

2023-01-02 09:01 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "release-date": "08 January 2023",
Change date to `09 January 2023`

2023-01-02 09:01 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "cves": "CVE-2022-42898",
`"cves": "CVE-2022-42898",` ----->
`"cves": "CVE-2022-42898,CVE-2022-41717,CVE-2022-41720",`

and 

`"fixes": [
                    "Fixes CVE-2022-42898,CVE-2022-41717,CVE-2022-41720 and PSIRT PVR0406812,PVR0410879,PVR0410611"
                 ]`
-----> `"fixes": []`

2023-01-02 11:40 UTC, mssachan approved these changes
LGTM

2023-01-02 11:40 UTC, merged