PSIRT/VA fix December for vpc block csi driver 4.3
IBM/ibm-satellite-storage pull request #255
Opened 2022-12-13 10:00 UTC by GunaKKIBM

2022-12-14 06:13 UTC, ashimagarg27 commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "cves": "CVE-2022-42898",
Fix "cves" key in "previous-revision":
expected value:
     "cves": "CVE-2022-1304,CVE-2016-3709"

2022-12-14 07:26 UTC, ashimagarg27 approved these changes

2022-12-20 09:58 UTC, GunaKKIBM commented
Closing this PR as 4.3 vpc block csi driver template is deprecated.

2022-12-22 03:00 UTC, GunaKKIBM commented
Re opened the PR - as 4.3 should still be supported on satellite.

2022-12-22 07:27 UTC, prankulmahajan approved these changes
lgtm

2022-12-22 07:35 UTC, nkkashyap approved these changes
lgtm

2023-01-02 08:59 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "cves": "CVE-2022-42898",
`"cves": "CVE-2022-42898",` ----->
`"cves": "CVE-2022-42898,CVE-2022-41717,CVE-2022-41720",`

and 

`"fixes": [
                    "Fixes CVE-2022-42898,CVE-2022-41717,CVE-2022-41720 and PSIRT PVR0406812,PVR0410879,PVR0410611"
                 ]`
-----> `"fixes": []`

2023-01-02 09:00 UTC, mssachan requested changes
LGTM. Just a minor change required

2023-01-02 11:38 UTC, mssachan approved these changes
LGTM

2023-01-02 11:38 UTC, merged