Mark 4.3.0 ibm-vpc-block-driver template unsupported
IBM/ibm-satellite-storage pull request #261
Opened 2023-01-03 17:54 UTC by prankulmahajan

2023-01-03 23:49 UTC, mssachan requested changes
Mark version `4.3` as `unsupported` in changelog.json as well
https://github.com/IBM/ibm-satellite-storage/blob/develop/config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json#L48-L51

2023-01-04 07:41 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> -        }
I think u removed one required `}`

2023-01-04 07:54 UTC, prankulmahajan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> -        }
Updated

2023-01-04 08:17 UTC, mssachan approved these changes
LGTM

2023-01-04 08:17 UTC, merged