ODF 4.11 release[DO NOT MERGE]
IBM/ibm-satellite-storage pull request #263
Opened 2023-01-09 08:08 UTC by gayathrimenath-ibm

2023-01-19 16:50 UTC, akgunjal approved these changes
LGTM

2023-01-20 02:31 UTC, mssachan requested changes

2023-01-20 02:31 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "release-date": "19 January 2023",
Change date to `23 Jan`

2023-01-20 02:31 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "fixes": ["UBI image update"]
No need to write `UBI image update`. Keep it empty

2023-01-20 02:31 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "cves": "",
Add all CVEs which are being fixed with the new revision

2023-01-20 02:31 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                "release-date": "19 January 2023",
Same here for all versions

2023-01-20 03:45 UTC, mssachan approved these changes
LGTM

2023-01-20 03:46 UTC, merged