VPC Block CSI Driver 5.1 release
IBM/ibm-satellite-storage pull request #283
Opened 2023-02-01 03:42 UTC by GunaKKIBM

2023-02-01 04:15 UTC, ambiknai commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/deployment.yaml
> +      labels:
We will make volumesnapshotclass "default"

2023-02-01 04:34 UTC, ambiknai commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/deployment.yaml
> +            - operator: Exists
We must add priorityClass here -system-node-critical

2023-02-01 04:34 UTC, ambiknai commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/deployment.yaml
> +          serviceAccountName: ibm-vpc-block-controller-sa
system-cluster-critical priorityClass must be added

2023-11-21 03:11 UTC, mssachan requested changes
Please compare all the files under new template version 5.1 with files of existing template version 5.0

2023-11-21 03:11 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/custom-parameters.json
> +      "description": "The ID of the resource group where your VPC is located. To retrieve this value, run the 'ibmcloud is vpc VPC-ID' command and note the Resource group field.",
update description as `The ID of the resource group where your VPC is located. You can find your resource group by running the 'ibmcloud is vpc VPC-ID' command and note the Resource group field.` similar to 5.0 version

2023-11-21 03:11 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/deployment.yaml
> +              image: icr.io/obs/storage/vpc-node-label-updater:v4.2.14
use latest image with security fixes here: latest version as of today is v4.2.15
Use latest images at other places as well

2023-11-21 03:11 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.0/metadata.json
> +  "status": "deprecated",
Do not deprecate existing version until new version is already in PROD

2023-11-21 03:11 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/metadata.json
> +      "value": "IBM knowledge center: https://www.ibm.com/support/knowledgecenter/SSRQ8T_1.4.0/csi_block_storage_kc_welcome.html"
This does not look to be correct link. Please refere version 5.0 for correct link.

2023-11-21 03:11 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/metadata.json
> +      "value": "4.10,4.11,4.12,4.13,4.14"
put `space` after every comma.
`"4.10,4.11,4.12,4.13,4.14"` ----> `"4.10, 4.11, 4.12, 4.13, 4.14"`

2023-11-21 03:11 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/5.1/storage-class-parameters.json
> +    {
Please compare this file with 5.0 version file. Lot of regex being removed. Please review

2023-11-21 03:13 UTC, mssachan commented
Also please update `changelog.json` with new version details in case you want to release this template in next stage push scheduled on 23rd November

2023-11-23 12:02 UTC, mssachan approved these changes
LGTM

2023-11-23 12:03 UTC, merged