UBI image update
IBM/ibm-satellite-storage pull request #291
Opened 2023-02-16 05:24 UTC by gayathrimenath-ibm

2023-02-16 06:18 UTC, akgunjal approved these changes
LGTM

2023-02-16 09:20 UTC, mssachan requested changes

2023-02-16 09:20 UTC, mssachan commented on .secrets.baseline
> +  "version": "0.13.1+ibm.47.dss",
@gayathrimenath-ibm Please upgrade `detect-secrets` tool and regenerate this file
`pre-commit autoupdate`
https://github.ibm.com/Whitewater/whitewater-detect-secrets/wiki/Developer-Tool-FAQs#how-do-i-upgrade-detect-secrets-to-a-newer-version

2023-02-16 09:20 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "release-date": "20 Feburary 2023",
`Feburary` --> `February`

2023-02-16 09:20 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "golang": "",
Add current golang version of the image

2023-02-16 09:20 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "golang": "",
Same here

2023-02-16 09:20 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "release-date": "20 Feburary 2023",
same typo here

2023-02-16 09:20 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                "golang": "",
Same here as mentioned above

2023-02-17 08:30 UTC, mssachan approved these changes
LGTM

2023-02-17 08:30 UTC, merged