ODF template refresh
IBM/ibm-satellite-storage pull request #309
Opened 2023-03-13 12:08 UTC by gayathrimenath-ibm

2023-03-14 06:22 UTC, akgunjal approved these changes
lgtm

2023-03-16 13:04 UTC, mssachan requested changes

2023-03-16 13:04 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
>              "status": "supported",
change status `supported` ---> `deprecated`

2023-03-16 13:04 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +            "previous-revision": {
No need to have any revision info once template is unsupported
Refer this: https://github.com/IBM/ibm-satellite-storage/blob/develop/config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json#L27

2023-03-16 13:04 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
>              "status": "supported",
`supported` --> `deprecated`

2023-03-16 13:04 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +            "previous-revision": {
same here

2023-03-17 07:45 UTC, mssachan approved these changes
LGTM

2023-03-17 07:46 UTC, merged