Add 2.7.1 version for vmware-vsphere-csi-driver
IBM/ibm-satellite-storage pull request #310
Opened 2023-03-17 06:01 UTC by asifdxtreme

2023-03-17 08:03 UTC, mssachan requested changes

2023-03-17 08:03 UTC, mssachan commented on config-templates/vmware/vsphere-csi-driver/2.7.1/metadata.json
> +    "revision": "7",
since this is new template version, change revision to `1`

2023-03-17 08:03 UTC, mssachan commented on config-templates/vmware/vsphere-csi-driver/2.7.1/deployment.yaml
> +    revision: 7
since this is new template version, change revision to `1`

2023-03-17 08:09 UTC, nkkashyap reviewed
Code change looks good, 
just need to reset `revision` to `1`,

2023-03-17 09:42 UTC, mssachan approved these changes
LGTM

2023-03-20 06:01 UTC, asifdxtreme commented
@gauravAggrahari Can we go ahead and merge this PR

2023-03-20 07:03 UTC, mssachan commented
@asifdxtreme Sure. 
FYI, this template version would be available in prod by end of the week ie. 24th March.

2023-03-20 07:06 UTC, merged