ODF 4.12 release
IBM/ibm-satellite-storage pull request #314
Opened 2023-03-24 05:11 UTC by gayathrimenath-ibm

2023-03-24 05:22 UTC, akgunjal approved these changes
lgtm

2023-03-31 06:56 UTC, akgunjal approved these changes
lgtm

2023-03-31 13:52 UTC, mssachan requested changes

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-local/4.12/deployment.yaml
> +    revision: 2
change revision to `1`

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-local/4.12/metadata.json
> +  "revision": "2",
change `revision` to `1`

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-local/4.12/storage-class.yaml
> +        app.kubernetes.io/revision: "2"
change `revision` to `1` at all places in this file

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-remote/4.12/deployment.yaml
> +    revision: 2
change `revision` to `1`

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-remote/4.12/metadata.json
> +  "revision": "2",
change `revision` to `1`

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +        "4.12": {
"4.12": {
            "status": "supported",
            "latest-revision": {
                "revision": "1",
                "release-date": "04 April 2023",
                "cves": "",
                "golang": "1.19.7",
                "ubi": "8.7-1085.1679482090",
                "new-features": [
                      "Initial release"
                ],
                "fixes": []
            }
        }

2023-03-31 13:52 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +        "4.12": {
```
 "4.12": {
        "status": "supported",
        "latest-revision": {
            "revision": "1",
            "release-date": "04 April 2023",
            "cves": "",
            "golang": "1.19.7",
            "ubi": "8.7-1085.1679482090",
            "new-features": [
                  "Initial release"
            ],
            "fixes": []
        }
    }
```

2023-04-01 13:45 UTC, mssachan approved these changes
LGTM

2023-04-01 13:46 UTC, merged