ODF template update
IBM/ibm-satellite-storage pull request #338
Opened 2023-06-12 04:47 UTC by gayathrimenath-ibm

2023-06-12 15:21 UTC, mssachan requested changes

2023-06-12 15:21 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "release-date": "17 May 2023",
Change release date to `19 May 2023` at all places.

2023-06-12 15:21 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "fixes": [""]
`"fixes": [""]` ---> `"fixes": []` at all places.

2023-06-12 15:21 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                "revision": "3",
Fix revision number here

2023-06-12 15:21 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                "revision": "3",
Fix revision number here

2023-06-12 15:21 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                "revision": "3",
Fix revision number here

2023-06-12 15:21 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "golang": "1.19.9",
Just verify if you have fixed following PSIRTs as well with the new images?
https://github.ibm.com/alchemy-containers/armada-storage/issues/4484
https://github.ibm.com/alchemy-containers/armada-storage/issues/4508
https://github.ibm.com/alchemy-containers/armada-storage/issues/4487
If YES, please add corresponding CVEs as well in the list.

2023-06-13 04:35 UTC, gayathrimenath-ibm commented on config-templates/redhat/odf-local/changelog.json
> +                "golang": "1.19.9",
Not added

2023-06-13 04:37 UTC, gayathrimenath-ibm commented
@mssachan could you please verify

2023-06-16 10:57 UTC, mssachan approved these changes
LGTM

2023-06-16 10:58 UTC, merged