VPC block CSI Driver golang builder support
IBM/ibm-satellite-storage pull request #401
Opened 2024-02-29 04:25 UTC by GunaKKIBM

2024-03-02 08:05 UTC, ashimagarg27 approved these changes

2024-03-03 10:25 UTC, mssachan commented on config-templates/ibm/ibm-vpc-block-csi-driver/changelog.json
> +                "golang": "",
update golang image. You can get golang version used for building image from Travis build which built & pushed the image.

2024-03-03 10:26 UTC, mssachan requested changes
Added minor comment

2024-03-04 06:50 UTC, prankulmahajan commented
@mssachan Updated

2024-03-04 06:51 UTC, mssachan approved these changes
LGTM

2024-03-04 06:51 UTC, merged