ODF 4.15 Release
IBM/ibm-satellite-storage pull request #410
Opened 2024-04-30 14:51 UTC by aayushsss1

ODF 4.15 Release 

1. Added three new parameters - 

- resourceProfile
- enableNFS
- useCephRBDAsDefaultStorageClass

2. Updated the Deployment File

2024-05-03 09:39 UTC, mssachan requested changes
Added minor comment. 
Also get approval from @derekpoindexter for the description of new parameters.

2024-05-03 09:39 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "release-date": "6 May 2024",
Update release date to `09 May 2024`

2024-05-03 09:39 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                "release-date": "6 May 2024",
same here

2024-05-06 13:22 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.15/custom-parameters.json
> +    "description": "Enable to set the Ceph RADOS block device (RBD) storage class as the default storage class during the deployment of OpenShift Data Foundation",
```suggestion
    "description": "Set the Ceph RADOS block device (RBD) storage class as the default storage class during the deployment of OpenShift Data Foundation",
```

2024-05-06 13:23 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.15/custom-parameters.json
> +    "description": "Provides an option to choose a resource profile based on the availability of resources during deployment. Choose between 'lean', 'balanced' and 'performance'.",
```suggestion
    "description": "Choose a resource profile based on the availability of resources during deployment. Choose between 'lean', 'balanced' and 'performance'.",
```

2024-05-06 13:24 UTC, derekpoindexter commented on config-templates/redhat/odf-local/4.15/custom-parameters.json
> +    "description": "Enabling this allows you to create exports using Network File System (NFS) that can then be accessed internally or externally from the OpenShift cluster",
```suggestion
    "description": "Allow exports from the Network File System (NFS) that can then be accessed internally or externally from the OpenShift cluster",
```

2024-05-06 13:25 UTC, derekpoindexter requested changes
see suggestions

2024-05-06 14:26 UTC, derekpoindexter approved these changes

2024-05-06 17:27 UTC, mssachan approved these changes
LGTM

2024-05-06 17:28 UTC, merged