refresh the ebs-csi-driver to latest CSI driver version 1.31.0
IBM/ibm-satellite-storage pull request #419
Opened 2024-05-30 09:10 UTC by gauravAggrahari

2024-05-31 05:53 UTC, nkkashyap requested changes

2024-05-31 05:53 UTC, nkkashyap commented on config-templates/aws/aws-ebs-csi-driver/changelog.json
> +        "1.12.0": {
it should be `1.31.0`

2024-06-04 06:27 UTC, mssachan approved these changes
Added minor comments

2024-06-04 06:27 UTC, mssachan commented on config-templates/aws/aws-ebs-csi-driver/1.31.0/metadata.json
> +      "value": "4.14,4.15"
Add space after comma

2024-06-04 06:27 UTC, mssachan commented on config-templates/aws/aws-ebs-csi-driver/1.31.0/deployment.yaml
> +      minAvailable: 1
change it to `2`

2024-06-04 06:27 UTC, mssachan commented on config-templates/aws/aws-ebs-csi-driver/changelog.json
> +                "release-date": "3 June 2024",
`3 June 2024` ---> `05 June 2024`

2024-06-04 10:24 UTC, mssachan approved these changes
lgtm

2024-06-04 10:49 UTC, nkkashyap approved these changes
lgtm

2024-06-04 10:49 UTC, merged