ODF 4.16 initial version
IBM/ibm-satellite-storage pull request #438
Opened 2024-09-27 10:46 UTC by gayathrimenath-ibm

2024-10-01 01:36 UTC, mssachan commented on config-templates/redhat/odf-local/4.14/deployment.yaml
> +            image: "icr.io/obs/armada-storage-secret:v1.2.48"
Need to update revision at all places since image is being changed

2024-10-01 01:36 UTC, mssachan commented on config-templates/redhat/odf-local/4.15/deployment.yaml
> +            image: "icr.io/obs/armada-storage-secret:v1.2.48"
same here

2024-10-01 01:47 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                    "ODF 4.16 new release"
`ODF 4.16 new release` ---> `Initial release`

2024-10-01 01:48 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                "golang": "1.22.1",
are you using common golang base image to build ODF images? If yes, please confirm if golang is `1.22.1` or `1.22.7`

2024-10-01 01:48 UTC, mssachan commented on config-templates/redhat/odf-remote/4.14/deployment.yaml
> +            image: "icr.io/obs/armada-storage-secret:v1.2.48"
same here

2024-10-01 01:48 UTC, mssachan commented on config-templates/redhat/odf-remote/4.15/deployment.yaml
> +            image: "icr.io/obs/armada-storage-secret:v1.2.48"
same here

2024-10-01 01:51 UTC, mssachan commented on config-templates/redhat/odf-remote/4.16/deployment.yaml
> +        controller-gen.kubebuilder.io/version: v0.12.0
`controller-gen.kubebuilder.io/version: v0.12.0` is different in ODF Local 4.16
So please confirm of kube-builder is correct here.

2024-10-01 01:59 UTC, mssachan commented on config-templates/redhat/odf-remote/changelog.json
> +                    "ODF 4.16 new release"
`ODF 4.16 new release` ---> `Initial release`

2024-10-01 01:59 UTC, mssachan requested changes
Changes looks good. Added minor comments. PTAL

2024-10-09 03:54 UTC, mssachan commented on config-templates/redhat/odf-local/changelog.json
> +                    "Sidecar golang updated to gv1.22.7-community-20240916"
Can you please clarify if sidecar images are updated to Go 1.22.7 but ODF image is still based on Go 1.21.13?

2024-10-09 03:55 UTC, mssachan approved these changes
LGTM

2024-10-09 13:33 UTC, gayathrimenath-ibm commented on config-templates/redhat/odf-local/changelog.json
> +                    "Sidecar golang updated to gv1.22.7-community-20240916"
yes, ODF images are still on 1.21.13

2024-10-09 15:53 UTC, merged